// <auto-generated />
namespace UnitOfWorkApp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class d : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d));
        
        string IMigrationMetadata.Id
        {
            get { return "202110111341020_d"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
